Repository tomassasovsky/radio-horizon.dart, pull requests merged in 2022-11, with the labels that each got.

#20 feat: setup for development environment
  bin/radio_garden_development.dart
  lib/src/settings.dart
  tool/clean_commands.dart
Labels: enhancement

#21 refactor: remove unused dependencies and converters
  bin/radio_garden_development.dart
  bin/radio_garden_production.dart
  lib/radio_garden.dart
  lib/src/converters.dart
  lib/src/error_handler.dart
  pubspec.yaml
Labels: enhancement

#12 feat: base for song recognition--including demo scripts and data models. missing service and command
  analysis_options.yaml
  bin/radio_garden_development.dart
  lib/src/models/song_recognition.dart
  lib/src/models/song_recognition.freezed.dart
  lib/src/models/song_recognition.g.dart
  lib/src/settings.dart
  pubspec.yaml
  sample.mp3
  tool/generate_sample.dart
  tool/identify_song.dart
Labels: enhancement

#25 feat: autocomplete for radio
  .github/workflows/radio_garden.yaml
  lib/src/commands/commands.dart
  lib/src/commands/music.dart
  lib/src/commands/radio.dart
  lib/src/models/radio_garden_response.dart
  lib/src/models/song_recognition.dart
  lib/src/models/song_recognition.freezed.dart
  lib/src/services/music.dart
  lib/src/settings.dart
  pubspec.yaml
Labels: enhancement

#29 fix: `/info` command type error
  lib/src/commands/info.dart
  pubspec.yaml
Labels: bug

#30 fix: ci build workflows
  .github/workflows/dart_package.yaml
  .github/workflows/radio_garden.yaml
  test/ensure_build_test.dart
Labels: bug

#31 feat: analytics
  bin/radio_garden_development.dart
  bin/radio_garden_production.dart
  lib/src/commands/info.dart
  lib/src/commands/music.dart
  lib/src/commands/radio.dart
  lib/src/models/docs.dart
  lib/src/models/models.dart
  lib/src/services/music.dart
  lib/src/settings.dart
  lib/src/util.dart
  pubspec.yaml
  tool/identify_song.dart
Labels: enhancement

#34 fix: prod not building
  bin/radio_garden_development.dart
  bin/radio_garden_production.dart
  lib/src/commands/music.dart
  lib/src/commands/radio.dart
  lib/src/dotenv.dart
  tool/clean_commands.dart
  tool/identify_song.dart
Labels: bug

#35 chore: modified publish_version.yaml to include the Dart entry file
  .github/workflows/publish_version.yaml
Labels: bug

#36 chore: now entering voice channels deafened
  lib/src/commands/commands.dart
  lib/src/commands/music.dart
Labels: enhancement

#37 chore: added github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/build.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/ci.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/performance.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/revert.md
  .github/ISSUE_TEMPLATE/style.md
  .github/ISSUE_TEMPLATE/test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#40 chore(hooks): pre-commit and commit-msg
  .github/hooks/commit-msg
  .github/hooks/pre-commit
  .vscode/settings.json
  .vscode/tasks.json
  lavalink.yml
  pubspec.yaml
Labels: chore

#42 feat: database integration
  .devcontainer/devcontainer.json
  bin/radio_garden_development.dart
  bin/radio_garden_production.dart
  lib/src/commands/radio.dart
  lib/src/models/models.dart
  lib/src/services/db.dart
  lib/src/services/services.dart
  lib/src/settings.dart
  pubspec.yaml
Labels: enhancement
